mybatis-plus:
  type-aliases-package: com.*.*.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ASSKK@_009*Joke
  redis:
    redisson:
      file: classpath:redisson.yml
    host: 127.0.0.1 # Redis服务器地址
    database: 2 # Redis数据库索引（默认为0）
    port: 1379 # Redis服务器连接端口
    password: ASSKK@_009*Joke # Redis服务器连接密码（默认为空）
    timeout: 10000ms # 连接超时时间（毫秒）
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms